version: '3'

services:
  redis:
    image: redis:latest
    network_mode: "host"
    volumes:
      - redis-data:/data
    restart: always
      
  registrator:
    build: .
    command: bash -c "python3 main.py"
    network_mode: "host"
    volumes:
      -  media:/media
      -  logs:/logs/data
    restart: always
    depends_on: 
      -  redis
  
volumes:
  redis-data:
  media:
  logs:
